graph TD
N0["excluded_file = 'convert_ipynb_to_md.ipynb'"]
N1["root_path = os.path.abspath('.')"]
N2["For: (dirpath, dirnames, filenames) in os.walk('.')"]
N3["For: filename in filenames"]
N2 --> N3
N4["full_path = os.path.join(dirpath, filename)"]
N3 --> N4
N5["If: (filename == 'README.ipynb')"]
N3 --> N5
N6["If: (filename == excluded_file and os.path.abspath(dirpath) != root_path)"]
N5 --> N6
N7["os.remove(full_path)"]
N6 --> N7
N8["print(f'Deleted file: full_path')"]
N6 --> N8