flowchart TD
n0["Func: convert_md_to_ipynb"]
n1["Converte um arquivo Markdown md para Jupyter Notebook ipynb Args: md_file str: Caminho para o arquivo Markdown"]
n0 --> n1
n2["notebook = nbformatv4new_notebook"]
n1 --> n2
n3["notebookcellsappendnbformatv4new_markdown_cellmd_content"]
n2 --> n3
n4["ipynb_file = md_filereplacemd ipynb"]
n3 --> n4
n5["Func: convert_ipynb_to_py"]
n6["Converte um arquivo Jupyter Notebook ipynb para Python Script py Args: ipynb_file str: Caminho para o arquivo Jupyter Notebook"]
n5 --> n6
n7["python_exporter = PythonExporter"]
n6 --> n7
n8["python_code _ = python_exporterfrom_notebook_nodenotebook"]
n7 --> n8
n9["py_file = ipynb_filereplaceipynb py"]
n8 --> n9
n10["excluded_file = convert_md_to_ipynbpy"]
n11["root_path = ospathabspath"]
n12{"For: dirpath dirnames filenames in oswalk"}
n13{"For: filename in filenames"}
n12 --> n13
n14["full_path = ospathjoindirpath filename"]
n13 --> n14
n15{"If: filenameendswithmd"}
n13 --> n15
n16{"If: filename == excluded_file and ospathabspathdirpath = root_path"}
n15 --> n16
n17["osremovefull_path"]
n16 --> n17
n18["printfArquivo excluído: full_path"]
n16 --> n18