flowchart TD
start([Start])
n1[function convert_md_to_ipynb()]
start --> n1
n2["""    Converte um arquivo Markdown (.md) para Jupyter Notebook (.ipynb).        Args:        md_file (str): Caminho para o arquivo Markdown.    """]
n1 --> n2
n3[notebook = nbformat.v4.new_notebook()]
n2 --> n3
n4[notebook.cells.append(nbformat.v4.new_markdown_cell(md_content))]
n3 --> n4
n5[ipynb_file = md_file.replace('.md', '.ipynb')]
n4 --> n5
n7[function convert_ipynb_to_py()]
start --> n7
n8["""    Converte um arquivo Jupyter Notebook (.ipynb) para Python Script (.py).        Args:        ipynb_file (str): Caminho para o arquivo Jupyter Notebook.    """]
n7 --> n8
n9[python_exporter = PythonExporter()]
n8 --> n9
n10[python_code, _ = python_exporter.from_notebook_node(notebook)]
n9 --> n10
n11[py_file = ipynb_file.replace('.ipynb', '.py')]
n10 --> n11
n13[excluded_file = 'convert_md_to_ipynb.py']
n11 --> n13
n14[root_path = os.path.abspath('.')]
n13 --> n14
n15((for (os.walk('.'))))
n14 --> n15
n16((for (filenames)))
n15 --> n16
n17[full_path = os.path.join(dirpath, filename)]
n16 --> n17
n18{if (filename.endswith('.md'))}
n17 --> n18
n19{else}
n18 --> n19
n20{if ((filename == excluded_file and os.path.abspath(dirpath) != root_path))}
n19 --> n20
n21[os.remove(full_path)]
n20 --> n21
n22[print(f'Arquivo excluído: {full_path}')]
n21 --> n22